### ISSUE TITLE
can't upvote/downvote twice same entry, buttons becomes inactive

### ISSUE THREAD

**Issue by dirmansebastian** [AkashaProject/dapp#103]
also, cannot downvote after upvote or vice versa

**Comment by bogdanbrezuica** [comment]
This is by design. You can only vote once on an entry

**Comment by dirmansebastian** [comment]
what about if the entry is edited? he add value to it, so he deserve another upvote :)

**Comment by bogdanbrezuica** [comment]
In Akasha, the voting mechanism is more than just a signal like on regular social media platforms. It is attached to an incentive mechanism and the ability to change your vote would make it much more gameable.
For example, let's say I downvote an entry and the majority of users upvote it. In this situation, I cannot collect Essence for my vote because it is not aligned with the majority. But if I could change it to an upvote I could collect Essence for it, so the incentive mechanism is compromised.

**Comment by dirmansebastian** [comment]
oh, that's right, thx for clarification
